2023-09-29 16:12:20,502 INFO    MainThread:20444 [wandb_setup.py:_flush():76] Current SDK version is 0.15.11
2023-09-29 16:12:20,502 INFO    MainThread:20444 [wandb_setup.py:_flush():76] Configure stats pid to 20444
2023-09-29 16:12:20,502 INFO    MainThread:20444 [wandb_setup.py:_flush():76] Loading settings from C:\Users\NEMESIS\.config\wandb\settings
2023-09-29 16:12:20,503 INFO    MainThread:20444 [wandb_setup.py:_flush():76] Loading settings from C:\Users\NEMESIS\Documents\NUS\Final Year Project\PRIMAL3\wandb\settings
2023-09-29 16:12:20,503 INFO    MainThread:20444 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-09-29 16:12:20,503 INFO    MainThread:20444 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-09-29 16:12:20,503 INFO    MainThread:20444 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'driver.py', 'program_abspath': 'C:\\Users\\NEMESIS\\Documents\\NUS\\Final Year Project\\PRIMAL3\\driver.py', 'program': 'C:\\Users\\NEMESIS\\Documents\\NUS\\Final Year Project\\PRIMAL3\\driver.py'}
2023-09-29 16:12:20,504 INFO    MainThread:20444 [wandb_init.py:_log_setup():528] Logging user logs to C:\Users\NEMESIS\Documents\NUS\Final Year Project\PRIMAL3\wandb\run-20230929_161220-5h12vmul\logs\debug.log
2023-09-29 16:12:20,504 INFO    MainThread:20444 [wandb_init.py:_log_setup():529] Logging internal logs to C:\Users\NEMESIS\Documents\NUS\Final Year Project\PRIMAL3\wandb\run-20230929_161220-5h12vmul\logs\debug-internal.log
2023-09-29 16:12:20,504 INFO    MainThread:20444 [wandb_init.py:init():568] calling init triggers
2023-09-29 16:12:20,504 INFO    MainThread:20444 [wandb_init.py:init():576] wandb.init called with sweep_config: {}
config: {'N_AGENTS': 8, 'N_ACTIONS': 5, 'EPISODE_LEN': 256, 'FOV_SIZE': 7, 'WORLD_SIZE': (10, 40), 'OBSTACLE_PROB': (0.0, 0.5), 'ACTION_COST': -0.3, 'IDLE_COST': -0.3, 'GOAL_REWARD': 0.0, 'COLLISION_COST': -2, 'BLOCKING_COST': -1, 'lr': 1e-05, 'GAMMA': 0.95, 'LAM': 0.95, 'CLIPRANGE': 0.2, 'MAX_GRAD_NORM': 10, 'ENTROPY_COEF': 0.01, 'VALUE_COEF': 0.08, 'POLICY_COEF': 10, 'VALID_COEF': 0.5, 'BLOCK_COEF': 0.5, 'N_EPOCHS': 10, 'N_ENVS': 16, 'N_MAX_STEPS': 30000000.0, 'N_STEPS': 1024, 'MINIBATCH_SIZE': 1024, 'DEMONSTRATION_PROB': 0.1, 'NET_SIZE': 512, 'NUM_CHANNEL': 4, 'GOAL_REPR_SIZE': 12, 'VECTOR_LEN': 4, 'SEED': 1234, 'USE_GPU_LOCAL': False, 'USE_GPU_GLOBAL': True, 'NUM_GPU': 1, 'RETRAIN': False, 'WANDB': True, 'TENSORBOARD': True, 'TXT_WRITER': True, 'ENTITY': 'yutong', 'TIME': '29-09-231612', 'EXPERIMENT_PROJECT': 'MAPF', 'EXPERIMENT_NAME': 'baseline', 'EXPERIMENT_NOTE': 'PRIMAL1 written by torch and trained by PPO, stop penalty=0', 'SAVE_INTERVAL': 500000.0, 'BEST_INTERVAL': 0, 'GIF_INTERVAL': 1000000.0, 'EVAL_INTERVAL': 16384, 'EVAL_EPISODES': 1, 'RECORD_BEST': False, 'MODEL_PATH': './models/MAPF/baseline29-09-231612', 'GIFS_PATH': './gifs/MAPF/baseline29-09-231612', 'SUMMARY_PATH': './summaries/MAPF/baseline29-09-231612', 'TXT_NAME': 'alg.txt'}
2023-09-29 16:12:20,505 INFO    MainThread:20444 [wandb_init.py:init():618] starting backend
2023-09-29 16:12:20,505 INFO    MainThread:20444 [wandb_init.py:init():622] setting up manager
2023-09-29 16:12:20,516 INFO    MainThread:20444 [backend.py:_multiprocessing_setup():107] multiprocessing start_methods=spawn, using: spawn
2023-09-29 16:12:20,520 INFO    MainThread:20444 [wandb_init.py:init():628] backend started and connected
2023-09-29 16:12:20,544 INFO    MainThread:20444 [wandb_init.py:init():720] updated telemetry
2023-09-29 16:12:20,545 INFO    MainThread:20444 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2023-09-29 16:12:22,455 ERROR   MainThread:20444 [wandb_init.py:init():779] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-09-29 16:12:22,609 ERROR   MainThread:20444 [wandb_init.py:init():1188] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Traceback (most recent call last):
  File "C:\Users\NEMESIS\Anaconda3\envs\PyTorch\lib\site-packages\wandb\sdk\wandb_init.py", line 1170, in init
    run = wi.init()
  File "C:\Users\NEMESIS\Anaconda3\envs\PyTorch\lib\site-packages\wandb\sdk\wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-09-29 16:12:23,632 WARNING MsgRouterThr:20444 [router.py:message_loop():77] message_loop has been closed
